[default_session]
preview_command = "eza --all --git --icons --color=always --width 100 {}"

[[session]]
name = "Dotfiles"
path = "~/.dotfiles"
startup_command = "nvim"

[[session]]
name = "Neovim config"
path = "~/.dotfiles/nvim/.config/nvim/"
startup_command = "nvim"

[[session]]
name = "GH Dash"
path = "~/repos"
startup_command = "gh dash"
